### ISSUE TITLE
Autofill doesn't use wood when placing stone furnaces

### ISSUE THREAD

**Issue by ElfLeaderMike** [3RaGaming/3Ra-Enhanced-Vanilla#10]
Title says it all

**Comment by samsail** [comment]
Hm. I'm not sure if it should, since autofill is most useful in the early game when you may need wood for power poles. Also wood is burned quickly. This could be added potentially at a lower priority than coal.

**Comment by stuudmuffin** [comment]
I think it should autofill wood. Lower priority "wood" be great.

**Comment by samsail** [comment]
https://github.com/3RaGaming/3Ra-Enhanced-Vanilla/commit/f75c50d28f9ed84b2132c17c3d386d52bc3422a1 Autofill now uses wood as lowest priority for all items
