### ISSUE TITLE
electric pole and underground belts

### ISSUE THREAD

**Issue by diilmac** [3RaGaming/3Ra-Enhanced-Vanilla#14]
when you remove pole and want to place next to, wires from removed pola are still visible, and there is a problem when you try place underground belts. i already reported it on discord but i think you still didnt solve it

**Comment by samsail** [comment]
These are base game issues but since 0.15 (which fixes them) might be a month away or more I went ahead and [committed a fix](https://github.com/3RaGaming/utils/commit/371fc79d31b4e6e17827433c9103a4ba641592ac).
